### ISSUE TITLE
Task a bit vague

### ISSUE THREAD

**Issue by Felipe-Hub** [ironhack-labs/lab-customer-analysis-round-4#2]
@sandrabosk Students freaked out a bit about the 'Normality check' task. Maybe, make it clear that you can just visually check for normality, plotting the distribution and seeing if it's bell shaped, also,maybe offer some extra material in case they want to check normality with pvalue or so (pvalue class is on the day after this lab).

**Comment by ironhack-edu** [comment]
added more context Thanks Felipe for your feedback :)
